from flask import Flask, render_template, request

app = Flask(__name__)

recipes = {
    "Spaghetti Bolognese": ["spaghetti", "tomato sauce", "ground beef", "onion"],
    "Caesar Salad": ["lettuce", "croutons", "parmesan", "chicken", "Caesar dressing"],
    "Grilled Cheese Sandwich": ["bread", "cheese", "butter"],
    "Fruit Salad": ["apple", "banana", "orange", "grapes"],
    "Pancakes": ["flour", "eggs", "milk", "baking powder", "butter", "syrup"],
    "Chicken Curry": ["chicken", "coconut milk", "curry paste", "onion", "garlic", "ginger", "rice"],
    "Chocolate Cake": ["flour", "sugar", "eggs", "cocoa powder", "baking powder", "butter", "vanilla extract"],
    "Mushroom Risotto": ["rice", "mushrooms", "onion", "vegetable broth", "parmesan", "butter"],
    "Chicken Parmesan": ["chicken breast", "bread crumbs", "marinara sauce", "mozzarella", "parmesan", "spaghetti"],
    "Beef Stew": ["beef", "carrots", "potatoes", "onion", "beef broth", "tomato paste"],
    "Cesar's Salad": ["romaine lettuce", "croutons", "parmesan cheese", "lemon juice", "Worcestershire sauce", "olive oil", "garlic", "egg", "anchovies"],
    "Hamburger": ["ground beef", "buns", "lettuce", "tomato", "onion", "pickles", "cheese", "ketchup", "mayonnaise"],
    "Lasagna": ["lasagna noodles", "ground beef", "tomato sauce", "ricotta cheese", "mozzarella cheese", "parmesan cheese"],
    "Tacos": ["tortillas", "ground beef", "lettuce", "tomato", "cheese", "salsa", "sour cream"],
    "Ratatouille": ["eggplant", "zucchini", "bell pepper", "onion", "tomato", "garlic", "herbs de Provence", "olive oil"],
    "Sushi": ["rice", "nori", "fish", "vegetables", "soy sauce", "wasabi", "pickled ginger"],
    "Chicken Noodle Soup": ["chicken", "carrots", "celery", "onion", "noodles", "chicken broth", "parsley"],
    "Garden Salad": ["lettuce", "tomato", "cucumber", "onion", "bell pepper", "olives", "feta cheese", "salad dressing"],
    "Omelette": ["eggs", "mushrooms", "spinach", "tomato", "cheese", "onion", "bell pepper"],
    "Beef Tacos": ["tortillas", "beef", "lettuce", "tomato", "cheese", "salsa", "sour cream"],
    "Stir Fry": ["rice", "chicken", "bell pepper", "onion", "broccoli", "soy sauce", "garlic", "ginger"],
    "Chicken Alfredo": ["fettuccine", "chicken", "heavy cream", "butter", "garlic", "parmesan", "parsley"],
    "Beef and Broccoli": ["beef", "broccoli", "soy sauce", "brown sugar", "garlic", "sesame oil", "cornstarch"],
    "Shrimp Scampi": ["linguine", "shrimp", "garlic", "butter", "lemon juice", "parsley", "white wine"],
    "Beef Bourguignon": ["beef", "carrots", "onion", "red wine", "beef broth", "mushrooms", "bacon", "garlic"],
    "Ravioli": ["ravioli", "tomato sauce", "parmesan", "basil", "olive oil"],
    "Beef and Guinness Stew": ["beef", "onion", "carrots", "potatoes", "Guinness", "beef broth", "tomato paste"],
    "Chicken Enchiladas": ["tortillas", "chicken", "onion", "cheese", "enchilada sauce", "sour cream"],
    "Shepherd's Pie": ["ground beef", "onion", "carrots", "peas", "mashed potatoes", "beef broth", "Worcestershire sauce"],
    "Baked Salmon": ["salmon", "lemon", "dill", "butter", "garlic", "olive oil"],
    "Beef Wellington": ["beef fillet", "puff pastry", "mushrooms", "prosciutto", "egg", "Dijon mustard"],
    "Eggplant Parmesan": ["eggplant", "bread crumbs", "marinara sauce", "mozzarella", "parmesan"],
    "Mongolian Beef": ["beef", "soy sauce", "brown sugar", "garlic", "ginger", "green onion", "sesame oil"],
    "Lemon Pepper Chicken": ["chicken", "lemon", "butter", "garlic", "pepper", "thyme", "parsley"],
    "French Toast": ["bread", "eggs", "milk", "vanilla extract", "cinnamon", "butter", "maple syrup"],
    "Tiramisu": ["ladyfingers", "espresso", "mascarpone", "eggs", "sugar", "cocoa powder"],
    "Cobb Salad": ["lettuce", "chicken", "avocado", "tomato", "bacon", "blue cheese", "hard-boiled eggs"],
    "Shrimp and Grits": ["shrimp", "grits", "bacon", "cheese", "green onion", "garlic", "lemon"],
    "Lamb Chops": ["lamb chops", "rosemary", "garlic", "olive oil", "salt", "pepper"],
    "Beef Ragu": ["beef", "tomato sauce", "onion", "carrots", "celery", "red wine", "garlic"],
    "Chicken Piccata": ["chicken", "lemon", "capers", "butter", "chicken broth", "flour"],
    "Fish and Chips": ["fish", "potatoes", "flour", "baking powder", "beer", "lemon", "tartar sauce"],
    "Pho": ["beef broth", "rice noodles", "beef", "onion", "bean sprouts", "basil", "lime", "hoisin sauce"],
    "Chicken and Dumplings": ["chicken", "carrots", "celery", "onion", "dumplings", "chicken broth", "flour"],
    "Baked Ziti": ["ziti pasta", "tomato sauce", "ricotta", "mozzarella", "parmesan", "garlic", "basil"],
    "Beef Tenders": ["beef", "soy sauce", "honey", "garlic", "sesame oil", "green onion", "ginger"],
    "Garlic Butter Shrimp": ["shrimp", "butter", "garlic", "lemon", "parsley", "red pepper flakes"],
    "Pot Roast": ["beef roast", "carrots", "potatoes", "onion", "beef broth", "garlic", "thyme"],
    "Cauliflower Fried Rice": ["cauliflower", "egg", "carrots", "peas", "onion", "soy sauce", "sesame oil"],
    "Lobster Bisque": ["lobster", "onion", "carrots", "celery", "tomato paste", "lobster stock", "heavy cream"],
    "Chicken Fajitas": ["chicken", "bell pepper", "onion", "tortillas", "salsa", "sour cream", "guacamole"],
    "Butternut Squash Soup": ["butternut squash", "onion", "carrots", "apple", "ginger", "vegetable broth", "cream"],
    "Lemon Garlic Butter Steak": ["steak", "butter", "garlic", "lemon", "thyme", "rosemary"],
    "Cauliflower Pizza Crust": ["cauliflower", "cheese", "eggs", "tomato sauce", "toppings of your choice"],
    "Beef Gyros": ["beef", "pita bread", "tzatziki sauce", "tomato", "onion", "lettuce"],
    "Creme Brulee": ["heavy cream", "egg yolks", "sugar", "vanilla extract"],
    "Chicken Tikka Masala": ["chicken", "tomato sauce", "yogurt", "cream", "onion", "garam masala", "ginger"],
    "Beef Chili": ["ground beef", "onion", "bell pepper", "beans", "tomato", "chili powder", "cumin"],
    "Beef Tamales": ["beef", "cornmeal", "corn husks", "chili powder", "cumin", "garlic", "onion"],
    "Pulled Pork Sandwiches": ["pork shoulder", "barbecue sauce", "buns", "coleslaw"],
    "Egg Fried Rice": ["rice", "egg", "carrots", "peas", "onion", "soy sauce", "sesame oil"],
    "Chicken Kebabs": ["chicken", "bell pepper", "onion", "zucchini", "olive oil", "garlic", "paprika"],
    "Beef Lo Mein": ["beef", "egg noodles", "mushrooms", "onion", "garlic", "soy sauce", "sesame oil"],
    "Ricotta Stuffed Shells": ["jumbo pasta shells", "ricotta cheese", "mozzarella", "parmesan", "tomato sauce"],
    "Beef Empanadas": ["beef", "onion", "bell pepper", "olives", "raisins", "cumin", "paprika"],
    "Sesame Chicken": ["chicken", "soy sauce", "honey", "garlic", "sesame oil", "green onion", "ginger"],
    "Vegetable Lo Mein": ["egg noodles", "mushrooms", "bell pepper", "carrots", "onion", "garlic", "soy sauce"],
    "Pesto Pasta": ["pasta", "basil", "pine nuts", "garlic", "olive oil", "parmesan", "lemon juice"],
    "Chicken Marsala": ["chicken", "marsala wine", "mushrooms", "onion", "garlic", "thyme", "flour"],
    "Lemon Butter Scallops": ["scallops", "butter", "garlic", "lemon", "parsley", "white wine"],
    "Vegetable Soup": ["carrots", "celery", "onion", "potatoes", "green beans", "corn", "vegetable broth"],
    "Zucchini Bread": ["zucchini", "flour", "sugar", "eggs", "cinnamon", "baking powder", "vanilla extract"],
    "Clam Chowder": ["clams", "potatoes", "onion", "celery", "bacon", "heavy cream", "thyme"],
    "Chicken Teriyaki": ["chicken", "soy sauce", "brown sugar", "mirin", "sake", "garlic", "ginger"],
    "Vegetable Lasagna": ["lasagna noodles", "spinach", "zucchini", "carrots", "ricotta cheese", "mozzarella", "marinara sauce"],
    "Chicken Wings": ["chicken wings", "hot sauce", "butter", "garlic powder", "paprika", "salt", "pepper"],
    "French Onion Soup": ["onion", "beef broth", "thyme", "baguette", "cheese"],
    "Bruschetta": ["baguette", "tomato", "garlic", "basil", "olive oil", "balsamic vinegar"],
    "Chicken Enchilada Casserole": ["tortillas", "chicken", "enchilada sauce", "cheese", "black beans", "corn"],
    "Beef Burritos": ["tortillas", "beef", "rice", "beans", "cheese", "salsa", "sour cream"],
    "Gnocchi": ["gnocchi", "tomato sauce", "basil", "olive oil", "parmesan"],
    "Chicken Cacciatore": ["chicken", "tomato sauce", "onion", "bell pepper", "mushrooms", "garlic"],
    "Sausage and Peppers": ["sausage", "bell pepper", "onion", "garlic", "tomato sauce", "Italian seasoning"],
    "Honey Garlic Salmon": ["salmon", "honey", "soy sauce", "garlic", "ginger", "lemon"],
    "Cajun Shrimp and Grits": ["shrimp", "grits", "bacon", "cheese", "bell pepper", "onion", "Cajun seasoning"],
    "Baked Chicken": ["chicken", "chilemon", "garlic", "thyme", "rosemary", "butter"],
    "Peanut Butter and Jelly Sandwich": ["bread", "peanut butter", "jelly"],
    "Cobbler": ["fruit", "sugar", "flour", "baking powder", "butter", "milk"],
    "Egg Salad": ["eggs", "mayonnaise", "mustard", "onion", "celery", "salt", "pepper"],
    "Lemonade": ["lemons", "sugar", "water", "ice"],
    "Garlic Bread": ["bread", "butter", "garlic", "parsley", "cheese"],
    "Banana Bread": ["bananas", "flour", "sugar", "eggs", "baking soda", "salt"],
    "Oatmeal Cookies": ["oats", "flour", "butter", "sugar", "eggs", "cinnamon", "baking soda"],
    "Cheesecake": ["cream cheese", "sugar", "eggs", "sour cream", "butter", "vanilla extract"],
    "Mashed Potatoes": ["potatoes", "butter", "milk", "salt", "pepper"],
    "Pesto Sauce": ["basil", "pine nuts", "garlic", "parmesan", "olive oil", "lemon juice"],
    "Ranch Dressing": ["mayonnaise", "sour cream", "buttermilk", "garlic", "onion", "herbs", "salt", "pepper"],
    "Salsa": ["tomatoes", "onion", "jalapeno", "cilantro", "lime", "salt", "pepper"],
    "Guacamole": ["avocado", "onion", "tomato", "lime", "cilantro", "jalapeno", "salt", "garlic"],
    "Hummus": ["chickpeas", "tahini", "olive oil", "garlic", "lemon juice", "cumin", "salt"],
    "Caprese Salad": ["tomato", "mozzarella", "basil", "olive oil", "balsamic vinegar", "salt", "pepper"],
    "Margarita Pizza": ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil", "salt"],
    "Tuna Salad": ["canned tuna", "mayonnaise", "celery", "onion", "pickles", "mustard", "salt", "pepper"],
    "Chicken Quesadilla": ["tortillas", "chicken", "cheese", "bell pepper", "onion", "sour cream", "salsa"],
    "Coleslaw": ["cabbage", "carrots", "mayonnaise", "sugar", "vinegar", "mustard", "salt", "pepper"],
    "Pasta Primavera": ["pasta", "bell pepper", "zucchini", "yellow squash", "mushrooms", "cream", "garlic",],
    "Apple Pie": ["apples", "sugar", "cinnamon", "butter", "flour", "lemon juice", "pie crust"],
    "Frittata": ["eggs", "potatoes", "onion", "bell pepper", "cheese", "milk", "spinach"],
    "Cinnamon Rolls": ["flour", "sugar", "yeast", "butter", "cinnamon", "brown sugar", "cream cheese", "vanilla extract"],
    "Ratatouille": ["eggplant", "zucchini", "bell pepper", "onion", "tomato", "garlic", "herbs de Provence", "olive oil"],
    "Shakshuka": ["eggs", "tomato", "bell pepper", "onion", "garlic", "cumin", "paprika", "chili flakes"],
    "Pumpkin Soup": ["pumpkin", "onion", "carrots", "ginger", "vegetable broth", "coconut milk", "curry powder"],
    "Gazpacho": ["tomato", "cucumber", "bell pepper", "onion", "garlic", "olive oil", "vinegar", "salt"],
    "French Toast": ["bread", "eggs", "milk", "vanilla extract", "cinnamon", "butter", "maple syrup"],
    "Cranberry Sauce": ["cranberries", "orange juice", "sugar", "cinnamon", "ginger", "nutmeg"],
    "Beef Jerky": ["beef", "soy sauce", "Worcestershire sauce", "garlic powder", "onion powder", "black pepper", "liquid smoke"],
    "Peanut Butter Cookies": ["peanut butter", "sugar", "egg", "vanilla extract", "baking soda", "salt", "chocolate chips"],
    "Raspberry Sorbet": ["raspberries", "sugar", "water", "lemon juice"],
    "Carrot Cake": ["carrots", "sugar", "flour", "eggs", "cinnamon", "baking soda", "walnuts", "cream cheese", "vanilla extract"],
    "Chicken Shawarma": ["chicken", "yogurt", "lemon", "garlic", "cumin", "paprika", "turmeric", "onion", "pita bread", "tahini sauce"],
    "Baba Ganoush": ["eggplant", "tahini", "garlic", "lemon juice", "olive oil", "salt", "paprika", "parsley"],
    "Risotto": ["rice", "white wine", "onion", "butter", "parmesan", "chicken broth", "mushrooms", "spinach"],
    "Gingerbread Cookies": ["flour", "ginger", "cinnamon", "baking soda", "butter", "sugar", "molasses", "egg"],
    "Tres Leches Cake": ["flour", "sugar", "baking powder", "milk", "vanilla extract", "condensed milk", "evaporated milk", "whipping cream"],
    "Mojito": ["mint leaves", "lime", "rum", "sugar", "club soda", "ice"],
    "Mimosa": ["champagne", "orange juice"],
    "White Russian": ["vodka", "coffee liqueur", "cream"],
    "Mai Tai": ["rum", "lime juice", "orgeat syrup", "triple sec", "dark rum", "pineapple juice", "ice"],
    "Old Fashioned": ["whiskey", "sugar", "bitters", "orange twist"],
    "Gin and Tonic": ["gin", "tonic water", "lime", "ice"],
    "Margarita": ["tequila", "triple sec", "lime juice", "salt", "ice"],
    "Manhattan": ["whiskey", "sweet vermouth", "bitters", "cherry"],
    "Martini": ["gin", "dry vermouth", "olive", "ice"],
    "Pina Colada": ["rum", "coconut cream", "pineapple juice", "pineapple", "ice"],
    "Sangria": ["red wine", "brandy", "orange juice", "fruit", "soda", "ice"],
    "Long Island Iced Tea": ["vodka", "tequila", "rum", "gin", "triple sec", "simple syrup", "lemon juice", "cola", "ice"],
    "Cosmopolitan": ["vodka", "triple sec", "cranberry juice", "lime juice"],
    "Whiskey Sour": ["whiskey", "lemon juice", "simple syrup", "ice"],
    "Bloody Mary": ["vodka", "tomato juice", "hot sauce", "Worcestershire sauce", "lemon juice", "celery salt", "pepper"],
    "Mojito": ["mint leaves", "lime", "rum", "sugar", "club soda", "ice"],
    "Mimosa": ["champagne", "orange juice"],
    "White Russian": ["vodka", "coffee liqueur", "cream"],
    "Mai Tai": ["rum", "lime juice", "orgeat syrup", "triple sec", "dark rum", "pineapple juice", "ice"],
    "Old Fashioned": ["whiskey", "sugar", "bitters", "orange twist"],
    "Gin and Tonic": ["gin", "tonic water", "lime", "ice"],
    "Margarita": ["tequila", "triple sec", "lime juice", "salt", "ice"],
    "Manhattan": ["whiskey", "sweet vermouth", "bitters", "cherry"],
    "Martini": ["gin", "dry vermouth", "olive", "ice"],
    "Pina Colada": ["rum", "coconut cream", "pineapple juice", "pineapple", "ice"],
    "Sangria": ["red wine", "brandy", "orange juice", "fruit", "soda", "ice"],
    "Long Island Iced Tea": ["vodka", "tequila", "rum", "gin", "triple sec", "simple syrup", "lemon juice", "cola", "ice"],
    "Cosmopolitan": ["vodka", "triple sec", "cranberry juice", "lime juice"],
    "Whiskey Sour": ["whiskey", "lemon juice", "simple syrup", "ice"],
    "Bloody Mary": ["vodka", "tomato juice", "hot sauce", "Worcestershire sauce", "lemon juice", "celery salt", "pepper"], 
    "Pesto Pizza": ["pizza dough", "pesto sauce", "mozzarella cheese", "cherry tomatoes", "fresh basil leaves"],
    "Pumpkin Soup": ["pumpkin", "onion", "garlic", "vegetable broth", "heavy cream", "nutmeg"],
    "Caramel Apples": ["apples", "caramel candies", "chopped nuts", "popsicle sticks"],
    "French Macarons": ["almond flour", "powdered sugar", "egg whites", "granulated sugar", "buttercream filling"],
    "Matcha Green Tea Latte": ["matcha powder", "milk", "honey"],
    "Zucchini Fritters": ["zucchini", "egg", "breadcrumbs", "parmesan cheese", "garlic powder"],
    "Red Velvet Cupcakes": ["flour", "cocoa powder", "butter", "sugar", "buttermilk", "red food coloring"],
    "Tomato Basil Bruschetta": ["baguette", "tomatoes", "fresh basil", "garlic", "olive oil", "balsamic vinegar"],
    "Mushroom Pizza": ["pizza dough", "mozzarella cheese", "mushrooms", "garlic", "olive oil"],
    "Pina Colada Cake": ["flour", "sugar", "baking powder", "pineapple juice", "coconut milk", "rum", "whipped cream"],
    "Caramel Popcorn": ["popcorn kernels", "butter", "brown sugar", "corn syrup", "baking soda"],
    "Cinnamon Rolls": ["flour", "butter", "sugar", "cinnamon", "yeast", "powdered sugar", "milk"],
    "Brussels Sprouts with Bacon": ["brussels sprouts", "bacon", "olive oil", "garlic", "balsamic vinegar"],
    "Baba Ganoush": ["eggplant", "tahini", "garlic", "lemon juice", "cumin", "smoked paprika"],
    "Sweet and Sour Chicken": ["chicken", "bell pepper", "pineapple", "onion", "ketchup", "rice vinegar", "brown sugar", "soy sauce"],
    "Raspberry Sorbet": ["raspberries", "sugar", "lemon juice"],
    "Pecan Pie": ["pecans", "sugar", "corn syrup", "butter", "eggs", "vanilla extract", "pie crust"],
    "Ratatouille": ["eggplant", "zucchini", "bell pepper", "onion", "tomato", "garlic", "herbs de Provence", "olive oil"],
    "Shrimp Scampi": ["linguine", "shrimp", "garlic", "butter", "lemon juice", "parsley", "white wine"],
    "Beef Bourguignon": ["beef", "carrots", "onion", "red wine", "beef broth", "mushrooms", "bacon", "garlic"],
    "Ravioli": ["ravioli", "tomato sauce", "parmesan", "basil", "olive oil"],
    "Beef and Guinness Stew": ["beef", "onion", "carrots", "potatoes", "Guinness", "beef broth", "tomato paste"],
    "Chicken Enchiladas": ["tortillas", "chicken", "onion", "cheese", "enchilada sauce", "sour cream"],
    "Shepherd's Pie": ["ground beef", "onion", "carrots", "peas", "mashed potatoes", "beef broth", "Worcestershire sauce"],
    "Baked Salmon": ["salmon", "lemon", "dill", "butter", "garlic", "olive oil"],
    "Beef Wellington": ["beef fillet", "puff pastry", "mushrooms", "prosciutto", "egg", "Dijon mustard"],
    "Eggplant Parmesan": ["eggplant", "bread crumbs", "marinara sauce", "mozzarella", "parmesan"],
    "Mongolian Beef": ["beef", "soy sauce", "brown sugar", "garlic", "ginger", "green onion", "sesame oil"],
    "Lemon Pepper Chicken": ["chicken", "lemon", "butter", "garlic", "pepper", "thyme", "parsley"],
    "French Toast": ["bread", "eggs", "milk", "vanilla extract", "cinnamon", "butter", "maple syrup"],
    "Tiramisu": ["ladyfingers", "espresso", "mascarpone", "eggs", "sugar", "cocoa powder"],
    "Cobb Salad": ["lettuce", "chicken", "avocado", "tomato", "bacon", "blue cheese", "hard-boiled eggs"],
    "Shrimp and Grits": ["shrimp", "grits", "bacon", "cheese", "green onion", "garlic", "lemon"],
    "Lamb Chops": ["lamb chops", "rosemary", "garlic", "olive oil", "salt", "pepper"],
    "Beef Ragu": ["beef", "tomato sauce", "onion", "carrots", "celery", "red wine", "garlic"],
    "Chicken Piccata": ["chicken", "lemon", "capers", "butter", "chicken broth", "flour"],
    "Fish and Chips": ["fish", "potatoes", "flour", "baking powder", "beer", "lemon", "tartar sauce"],
    "Pho": ["beef broth", "rice noodles", "beef", "onion", "bean sprouts", "basil", "lime", "hoisin sauce"],
    "Chicken and Dumplings": ["chicken", "carrots", "celery", "onion", "dumplings", "chicken broth", "flour"],
    "Baked Ziti": ["ziti pasta", "tomato sauce", "ricotta", "mozzarella", "parmesan", "garlic", "basil"],
    "Beef Tenders": ["beef", "soy sauce", "honey", "garlic", "sesame oil", "green onion", "ginger"],
    "Garlic Butter Shrimp": ["shrimp", "butter", "garlic", "lemon", "parsley", "red pepper flakes"],
    "Pot Roast": ["beef roast", "carrots", "potatoes", "onion", "beef broth", "garlic", "thyme"],
    "Cauliflower Fried Rice": ["cauliflower", "egg", "carrots", "peas", "onion", "soy sauce", "sesame oil"],
    "Lobster Bisque": ["lobster", "onion", "carrots", "celery", "tomato paste", "lobster stock", "heavy cream"],
    "Chicken Fajitas": ["chicken", "bell pepper", "onion", "tortillas", "salsa", "sour cream", "guacamole"],
    "Butternut Squash Soup": ["butternut squash", "onion", "carrots", "apple", "ginger", "vegetable broth", "cream"],
    "Lemon Garlic Butter Steak": ["steak", "butter", "garlic", "lemon", "thyme", "rosemary"],
    "Cauliflower Pizza Crust": ["cauliflower", "cheese", "eggs", "tomato sauce", "toppings of your choice"],
    "Beef Gyros": ["beef", "pita bread", "tzatziki sauce", "tomato", "onion", "lettuce"],
    "Creme Brulee": ["heavy cream", "egg yolks", "sugar", "vanilla extract"],
    "Chicken Tikka Masala": ["chicken", "tomato sauce", "yogurt", "cream", "onion", "garam masala", "ginger"],
    "Beef Chili": ["ground beef", "onion", "bell pepper", "beans", "tomato", "chili powder", "cumin"],
    "Beef Tamales": ["beef", "cornmeal", "corn husks", "chili powder", "cumin", "garlic", "onion"],
    "Pulled Pork Sandwiches": ["pork shoulder", "barbecue sauce", "buns", "coleslaw"],
    "Egg Fried Rice": ["rice", "egg", "carrots", "peas", "onion", "soy sauce", "sesame oil"],
    "Chicken Kebabs": ["chicken", "bell pepper", "onion", "zucchini", "olive oil", "garlic", "paprika"],
    "Beef Lo Mein": ["beef", "egg noodles", "mushrooms", "onion", "garlic", "soy sauce", "sesame oil"],
    "Ricotta Stuffed Shells": ["jumbo pasta shells", "ricotta cheese", "mozzarella", "parmesan", "tomato sauce"],
    "Beef Empanadas": ["beef", "onion", "bell pepper", "olives", "raisins", "cumin", "paprika"],
    "Sesame Chicken": ["chicken", "soy sauce", "honey", "garlic", "sesame oil", "green onion", "ginger"],
    "Vegetable Lo Mein": ["egg noodles", "mushrooms", "bell pepper", "carrots", "onion", "garlic", "soy sauce"],
    "Pesto Pasta": ["pasta", "basil", "pine nuts", "garlic", "olive oil", "parmesan", "lemon juice"],
    "Chicken Marsala": ["chicken", "marsala wine", "mushrooms", "onion", "garlic", "thyme", "flour"],
    "Lemon Butter Scallops": ["scallops", "butter", "garlic", "lemon", "parsley", "white wine"],
    "Vegetable Soup": ["carrots", "celery", "onion", "potatoes", "green beans", "corn", "vegetable broth"],
    "Zucchini Bread": ["zucchini", "flour", "sugar", "eggs", "cinnamon", "baking powder", "vanilla extract"],
    "Clam Chowder": ["clams", "potatoes", "onion", "celery", "bacon", "heavy cream", "thyme"],
    "Chicken Teriyaki": ["chicken", "soy sauce", "brown sugar", "mirin", "sake", "garlic", "ginger"],
    "Vegetable Lasagna": ["lasagna noodles", "spinach", "zucchini", "carrots", "ricotta cheese", "mozzarella", "marinara sauce"],
    "Chicken Wings": ["chicken wings", "hot sauce", "butter", "garlic powder", "paprika", "salt", "pepper"],
    "French Onion Soup": ["onion", "beef broth", "thyme", "baguette", "cheese"],
    "Bruschetta": ["baguette", "tomato", "garlic", "basil", "olive oil", "balsamic vinegar"],
    "Chicken Enchilada Casserole": ["tortillas", "chicken", "enchilada sauce", "cheese", "black beans", "corn"],
    "Beef Burritos": ["tortillas", "beef", "rice", "beans", "cheese", "salsa", "sour cream"],
    "Gnocchi": ["gnocchi", "tomato sauce", "basil", "olive oil", "parmesan"],
    "Chicken Cacciatore": ["chicken", "tomato sauce", "onion", "bell pepper", "mushrooms", "garlic"],
    "Sausage and Peppers": ["sausage", "bell pepper", "onion", "garlic", "tomato sauce", "Italian seasoning"],
    "Honey Garlic Salmon": ["salmon", "honey", "soy sauce", "garlic", "ginger", "lemon"],
    "Cajun Shrimp and Grits": ["shrimp", "grits", "bacon", "cheese", "bell pepper", "onion", "Cajun seasoning"],
    "Baked Chicken": ["chicken", "chilemon", "garlic", "thyme", "rosemary", "butter"]



} 


def find_possible_recipes(ingredients):
    possible_recipes = []
    for recipe, recipe_ingredients in recipes.items():
        if all(ingredient in ingredients for ingredient in recipe_ingredients):
            possible_recipes.append(recipe)
    return possible_recipes

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/find_recipes', methods=['POST'])
def find_recipes():
    user_input = request.form['ingredients']
    user_ingredients = [ingredient.strip() for ingredient in user_input.split(",")]

    possible_recipes = find_possible_recipes(user_ingredients)

    if possible_recipes:
        return render_template('results.html', user_input=user_input, possible_recipes=possible_recipes)
    else:
        return render_template('no_results.html')

if __name__ == '__main__':
    app.run(debug=True)